config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :items do
    resources :photos, only: [:create]
  end

  resources :users, only: [:show] do
    resources :carts do
      resources :cart_lines
    end
    resources :orders
  end

  namespace :static do
    resources :team, :contact, :ui_kit, only: [:index]
  end

  root 'items#index'
  
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_lines
  has_many :items, through: :cart_lines
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :is_owner, only: [:show, :update, :destroy, :index, :edit]
before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :show, :index]

def show
    puts "$" * 60
    puts "Salut, je suis dans le serveur pour l'affichage du panier de l'utilisateur"
    @cart = Cart.find(params[:id])
    @cart_lines = CartLine.where(:cart_id => params[:id])
    puts "Ceci est le contenu du hash params : #{params}"
    puts "$" * 60
    @total_price = 0.0
    puts "Le total price est bien initialisé"
    puts "$" * 60
  end

  def new
    @cart = Cart.new
  end

  def create
    @cart = Cart.new(user_id = current_user.id)
    if @cart.save
      flash[:success] = "Cart created"
      #redirect_to controller:'carts', action: 'show', id: @cart.id
    else
      render root_path
    end
  end

  def update
    puts "$" * 60
    puts "Salut, je suis dans le serveur pour une mise à jour du panier de l'utilisateur"
    puts "Ceci est le contenu du hash params : #{params}"
    ok = false
    if !params[:id].nil? && !params[:item_id].nil?
      cart_line_saved = CartLine.create("cart_id" => params[:id], "item_id" => params[:item_id])
      if cart_line_saved
        ok = true
        redirect_to user_cart_path(current_user.id, params[:id]), notice: 'Cette superbe photo de chaton(s) a bien été ajoutée à ton panier !'
      end
    end
    if !ok
      redirect_to item_path(params[:item_id])
    end
    puts "$" * 60
  end

  def destroy
    puts "$" * 60
    puts "Salut, je suis dans le serveur pour une suppression de toutes les lignes d'un panier"
    puts "Ceci est le contenu du hash params : #{params}"
    puts "cart_id : #{params[:id]}"
    @cart_lines = CartLine.where(:cart_id => params[:id])
    if !@cart_lines.nil? && @cart_lines.length > 0
      @cart_lines.length.times do |index|
        @cart_lines[index].destroy
      end
      redirect_to root_path, notice: 'Ton panier a bien été vidé !'
    end
  end

  private
  def is_owner
    if Cart.find_by(user_id:params[:user_id]).id.to_i != params[:id].to_i
      redirect_to "/"
      flash[:warning] = "You cannot see other users' carts!"
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<% if !@cart.nil? && !@cart_lines.nil? && @cart_lines.length > 0 %>
  <div class="container-show p-5">
    <div class="container-fluid" id="sub-container">
      <div class="col-md-12 p-5 cart">
        <div class="title">
          <div class="row">
            <div class="col">
             <h4><b>Shopping Cart</b></h4>
            </div>
          </div>
        </div>
        <% @cart_lines.each do |cart_line| %>
          <% @total_price += cart_line.item.price %>
          <div class="row border-top border-bottom">
            <div class="row main align-items-center">
              <div class="col-2"><img class="img-fluid" src=<%= cart_line.item.image_url %> alt=<%= cart_line.item.image_url %>></div>
              <div class="col">
                <div class="row text-muted">Kitten</div>
                <div class="row"><%= cart_line.item.title %></div>
              </div>
              <div class="col">Price &euro; <%= number_to_currency(cart_line.item.price, separator: ",", delimiter: "", format: "%n %u") %><span class="close"><%= link_to "Delete product", user_cart_cart_line_path(@cart.user.id, @cart.id, cart_line.id), method: "delete", class: "btn btn-sm btn-danger" %></span></div>
            </div>
          </div>
        <% end %>
        <div class="check-out-container">
          <div class="container col-12" id="sub-checkout">
            <div class="p-2">
              <button class="btn-empty btn"><%= link_to 'Empty Cart', user_cart_path(@cart.user.id, @cart.id), method: :delete, data: { confirm: "Are you sure? " }, class: "button is-danger" %></button>
            </div>
            <div class="p-2">
              <h4>
                <span>Total:</span> <%= number_to_currency(@total_price, unit: "€", separator: ",", delimiter: "", format: "%n %u") %>
              </h4>
            </div>
            <div class="">
              <%= button_to "Confirm your command", checkout_create_path(total: @total_price), class: "btn btn-primary btn-sm", role: "button", remote: true, form: { id: "checkout-button" }%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <%= link_to "The cart is empty, click to continue your shopping  <<------------------", root_path %>
<% end %>