config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :items do
    resources :photos, only: [:create]
  end

  resources :users, only: [:show] do
    resources :carts do
      resources :cart_lines
    end
    resources :orders
  end

  namespace :static do
    resources :team, :contact, :ui_kit, only: [:index]
  end

  root 'items#index'
  
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :carts

  has_one_attached :photo
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :is_admin?, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    # Méthode qui récupère tous les photos et les envoie à la view index (index.html.erb) pour affichage
    @items = Item.all
    puts "$" * 60
    puts "Voici le nombre de photos dans la base : #{@items.length}"
    puts "$" * 60
  end

  def show
    # Méthode qui récupère la photo concernée et l'envoie à la view show (show.html.erb) pour affichage
    @item = get_item 
  end

  def new
    # Méthode qui crée une photo vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    @new_item = Item.new
  end

  def create
    # Méthode qui créé une photo à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur "admin"
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher la photo créée)
    puts "$" * 60
    puts "Salut, je suis dans le serveur pour une création"
    puts "Ceci est le contenu du hash params : #{params}"
    puts "Trop bien ! Et ceci est ce que l'utilisateur a passé dans le champ title : #{params["title"]}"
    @item = Item.new("title" => params[:title],
                     "description" => params[:description],
                     "price" => params[:price],
                     "image_url" => params[:image_url])
    if @item.save # essaie de sauvegarder en base @item
      # si ça marche, il redirige vers la page d'index du site
      redirect_to items_path, status: :ok, notice: 'Ta superbe photo de chaton(s) a bien été créée en base pour la postérité !'
    else
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      render 'new'
    end
    puts "$" * 60
  end

  def edit
    # Méthode qui récupère la photo concernée et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    @item = get_item 
  end

  def update
    # Méthode qui met à jour la photo à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur "admin"
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher la photo modifiée)
    puts "$" * 60
    puts "Salut, je suis dans le serveur pour une mise à jour"
    puts "Ceci est le contenu du hash params : #{params}"
    puts "Trop bien ! Et ceci est ce que l'utilisateur a passé dans le champ title : #{params["title"]}"
    ok = false
    @item = get_item 
    if !params[:title].nil? && !params[:price].nil? && !params[:image_url].nil?
      item_saved = @item.update("title" => params[:title], # essaie de sauvegarder en base @item
                                "description" => params[:description],
                                "price" => params[:price],
                                "image_url" => params[:image_url])
      if item_saved
        # si ça a marché, il redirige vers la méthode index
        ok = true
        @item = get_item
        redirect_to items_path, status: :ok, notice: 'Ta superbe photo de chaton(s) a bien été mise à jour en base : elle est bien plus "attractive" désormais !'
      end
    end
    if !ok
      # sinon, il render la view edit (qui est celle sur laquelle on est déjà)
      render 'edit'
    end
    puts "$" * 60
  end

  def destroy
    # Méthode qui récupère la photo concernée et la détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    puts "$" * 60
    puts "Salut, je suis dans le serveur pour une suppression"
    puts "Ceci est le contenu du hash params : #{params}"
    puts "item_id : #{params[:id]}"
    @item = get_item 
    if !@item.nil?
      @item.destroy
      redirect_to items_path, status: :ok, notice: 'Ta photo "ratée" a bien été supprimée en base : plus personne ne saura que tu as un jour osé la proposer !'
    end
    puts "$" * 60
  end

  private

  def get_item
    item_id = params[:id].to_i
    puts "$" * 60
    puts "item_id : #{item_id}"
    @item = Item.find_by(id: item_id)
    puts "item : #{@item}"
    puts "$" * 60
    @item
  end

  def is_admin?
    item = get_item
    puts "$" * 60
    puts "Salut, je suis dans le serveur pour une vérification du statut de l'utilisateur connecté"
    puts "item : #{@item}"
    puts "admin? : #{current_user.id.to_s == '1'}"
    puts "$" * 60
    unless admin?
      redirect_to items_path, notice: "Vous n'êtes pas l'administrateur du site!"
    end
  end
end

app/views/items/edit.html.erb
<% if !@item.nil? && user_signed_in? && admin? %>
<div class="container-fluid" id="box-container-edit">
  <div class="sub-container">
    <div>
      <div class=" justify-center p-5">
        <h3>Modifie les détails de ta photo n°<%= @item.id %></h3>
      </div>
      <% if !@item.nil? && @item.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <p>Nous n'avons pas réussi à mettre à jour les détails de la photo pour la (ou les) raison(s) suivante(s) :</p>
          <ul>
            <% @item.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <form class="">
        <%= form_tag item_path(@item.id), method: "post" do %>
          <input type="hidden" name ="_method" value="put">
          <div class="justify-center">
            <h3><label for="validationServer01"><%= label_tag 'Titre' %></label></h3>
          </div>
          <div class="form-row justify-center">
            <div class=" mb-3">
              <%= text_field_tag 'title', (@item.title if !@item.title.nil?), size: 30, minlength: 5, maxlength: 40 %>
            </div>
          </div>
          <div class=" justify-center">
            <h3><label for="validationServer02"><%= label_tag 'Description' %></label></h3>
          </div>
          <div class="justify-center">
              <%= text_area_tag 'description', (@item.description if !@item.description.nil?), size: "50x5", minlength: 20, maxlength: 1000 %>
          </div>
          <div class=" pt-4 justify-center">
           <label for="validationServerUsername"><%= label_tag 'Prix en euros' %></label>
          </div>
          <div class=" mb-3 justify-center">
            <div class="input-group justify-center">
              <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupPrepend3">€</span>
              </div>
              <%= number_field_tag 'price', (@item.price if !@item.price .nil?), min: 1, max: 1000, step: 0.05 %>
              <div class="invalid-feedback">
                Please choose a price.
              </div>
            </div>
          </div>
          <div class=" justify-center">
            <label for="validationServer03"><%= label_tag 'URL' %></label>
          </div>
          <div class="form-row justify-center">
            <div class=" mb-3">
              <%= text_field_tag 'image_url', (@item.image_url if !@item.image_url.nil?), size: 50, minlength: 20, maxlength: 140 %>
              <div class="invalid-feedback">
                Please provide an url.
              </div>
            </div>
          </div>
          <div class="justify-center" id="button-resgister">
            <%= submit_tag "Enregistrer cette nouvelle version de ta photo" %>
          </div>
        <% end %>
        <div class=" mb-3">
          <%= form_tag item_photos_path(@item), multipart: true do %>
            <%= file_field_tag :photo %>
            <%= submit_tag "mettre à jour" %>
          <% end %>
        </div>
        <BR>
        <div class=" justify-center">
          <p>
            <a href="<%= item_path(@item.id) %>" class="btn btn-danger btn-sm" role="button" data-confirm="Es-tu certain de vouloir supprimer définitivement cette photo?" data-method="DELETE">Supprimer cette photo</a>
          </p>
        </div>
      <% elsif @item.nil? %>
        <div class="alert alert-danger" role="alert">
          <p>Aucune photo de n°<%= params[:id] %> n'existe dans la base!</p>
        </div>
      <% else %>
        <div class="alert alert-danger" role="alert">
          <p>Tu n'es pas l'admin de ce site : tu n'es donc pas autorisé à modifier les détails de la photo en base!</p>
        </div>
      <% end %>
      </form>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="bg-index">
  <div class="box-welcome-container">
    <div class="box-welcome-sub p-4">
      <div class="box-content">
        <p class="line-1 anim-typewriter text-dark">KittenMarket.com</p>
      </div>
    </div>
  </div>
  <div class="container text-center border p-4" id="box-photos">
    <div id="">
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <% @items.each do |item| %>
            <div class="col-md-3" style="float:left">
              <div class="card mb-2">
                <img class="card-img-top"
                  src=<%= item.image_url %> alt=<%= item.image_url %>>
                <div class="card-body">
                  <h4 class="card-title"><%= item.title %></h4>
                  <p class="card-text"><%= item.description %></p>
                  <button class="button-cart btn"><%= link_to "Photo n°#{item.id}", item_path(item.id)%></button>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<% if user_signed_in? && admin? %>
  <div class="container-fluid" id="box-container-new">
    <div class="sub-container">
      <div class="text-dark">
        <% if !@item.nil? && @item.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <p>Nous n'avons pas réussi à ajouter la photo pour la (ou les) raison(s) suivante(s) :</p>
            <ul>
              <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <% if !@item.nil? && @item.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <p>Nous n'avons pas réussi à mettre à jour les détails de la photo pour la (ou les) raison(s) suivante(s) :</p>
            <ul>
              <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <form class="">
          <h1 class="text-center">Ajoute une photo de chaton(s) !</h1>
          <%= form_tag url_for(action: 'create'), method: "post" do %>
            <input type="hidden" name ="_method" value="put">
            <div class="justify-center">
              <h3><label for="validationServer01"><%= label_tag 'Titre' %></label></h3>
            </div>
            <div class="form-row justify-center">
              <div class="">
                <%= text_field_tag 'title', (@item.title if !@item.nil?), size: 50, minlength: 5, maxlength: 40 %>
              </div>
            </div>
            <div class=" justify-center">
              <h3><label for="validationServer02"><%= label_tag 'Description' %></label></h3>
            </div>
            <div class="justify-center">
                <%= text_area_tag 'description', (@item.description if !@item.nil?), size: "100x5", minlength: 20, maxlength: 1000 %>
            </div>
            <div class=" pt-4 justify-center">
            <label for="validationServerUsername"><%= label_tag 'Prix en euros' %></label>
            </div>
            <div class=" mb-3 justify-center">
              <div class="input-group justify-center">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="inputGroupPrepend3">€</span>
                </div>
                <%= number_field_tag 'price', (@item.price if !@item.nil?), min: 1, max: 1000, step: 0.05 %>
                <div class="invalid-feedback">
                  Please choose a price.
                </div>
              </div>
            </div>
            <div class=" justify-center">
              <label for="validationServer03"><%= label_tag 'URL' %></label>
            </div>
            <div class="form-row justify-center">
              <div class="">
                <%= text_area_tag 'image_url', (@item.image_url if !@item.nil?), size: "100", minlength: 20, maxlength: 140 %>
                <div class="invalid-feedback">
                  Please provide an url.
                </div>
              </div>
            </div>
            <div class="justify-center" id="button-resgister">
              <%= submit_tag "Enregistrer cette photo" %>
            </div>
          <% end %>
          <BR>
          <% elsif !admin? %>

          <div class="alert alert-danger" role="alert">
            <p>Tu n'es pas l'admin de ce site : tu n'es donc pas autorisé à ajouter une photo!</p>
          </div>

          <% else %>

            <div class="alert alert-danger" role="alert">
              <p>Tu n'es pas connecté : tu n'es donc pas autorisé à ajouter une photo!</p>
            </div>

          <% end %>
        </form>
      </div>
    </div>
  </div>

app/views/items/show.html.erb
<div class="show-bg">
  <BR>
  <BR>
  <section class="ftco-section">
    <% if !@item.nil? %>
      <div class="container " id="card-box">
        <div class="card-show mb-3 container-fluid" >
          <img class="card-img-show img-fluid" src=<%= @item.image_url %> alt=<%= @item.image_url %>>
          <div class="card-body text-center p-2">
            <h5 class="card-title"><%= @item.title %></h5>
            <p class="card-text"><p class="content"><%= @item.description %></p>
            <p>Son prix : <%= number_with_precision(@item.price, :precision => 2, :delimiter => ' ', :separator => ',') %> &euro;</p>
            <p>La date d'ajout de la photo : <%= @item.created_at.strftime("%d/%m/%Y à %T %z") %></p>
            <p>La date de dernière modification des détails de la photo : <%= @item.updated_at.strftime("%d/%m/%Y à %T %z") %></p>
          </div>
          <div>
            <% if user_signed_in? && admin? %>
              <p>
                <a href="<%= edit_item_path(@item.id) %>" class="btn btn-primary btn-sm" role="button">Modifier ou supprimer ma photo</a>
              </p>
            <% end %>
          </div>
          <div>
          <% if user_signed_in? && !admin? %>
            <p>
              <%= button_to "Ajouter cette photo à mon panier", user_cart_path(current_user.id, current_user.cart.id), params: {item_id: @item.id}, method: :put, class: "btn btn-primary btn-sm", role: "button" %>
            </p>
          <% end %>
        </div>
        <br />
        </div>
      </div>
    <% else %>
      <div class="alert alert-danger" role="alert">
        <p>Aucune photo de n°<%= params[:id] %> n'existe dans la base!</p>
      </div>
    <% end %>
  </section>
</div>