config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :items do
    resources :photos, only: [:create]
  end

  resources :users, only: [:show] do
    resources :carts do
      resources :cart_lines
    end
    resources :orders
  end

  namespace :static do
    resources :team, :contact, :ui_kit, only: [:index]
  end

  root 'items#index'
  
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">x</span>
    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="fk-footer">
  <footer class="footer-4">
    <div class="container">
      <div class="row ">
        <div class="col-md-8 text-md-right mt-2 pt-1">
          <p class="copyright ">Copyright &copy; KittenMarket. All rights reserved.</p>
        </div>
      </div>
    </div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<div class="box-div">
  <nav class="navbar navbar-expand-lg">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon">Menu</span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="collapse navbar-collapse justify-center " id="navbarNavAltMarkup">
        <ul class="navbar-nav">
          <li class="nav-item nav-link">
            <button class="fk-nav"><%= link_to "Home", root_path, class: "nav-link" %></button>
          </li>
          <li class="nav-item nav-link">
            <button class="fk-nav "><%= link_to "Contact", static_contact_index_path, class: "nav-link" %></button>
          </li>
          <% if !user_signed_in? %>
            <li class="nav-item nav-link">
              <button class="fk-nav "><%= link_to "Register", new_user_registration_path, class: "nav-link" %></button>
            </li>
            <li class="nav-item nav-link">
              <button class="fk-nav "><%= link_to "Login", new_user_session_path, class: "nav-link" %></button>
            </li>
          <% else %>
            <li class="nav-item nav-link">
              <button class="fk-nav "><%= link_to "Profile", user_path(current_user.id), class: "nav-link" %></button>
            </li>
            <li class="nav-item nav-link">
              <button class="fk-nav "><%= link_to "Log-out", destroy_user_session_path, method: :delete, :data => {:confirm => "Êtes-vous sûr de vouloir vous déconnecter ?"}, class: "nav-link" %></button>
            </li>
            <% if user_signed_in? && admin? %>
              <li class="nav-item nav-link">
                <button class="fk-nav "><%= link_to "Add an item", new_item_path, class: "nav-link" %></button>
              </li>
            <% end %>
            <% if user_signed_in? && !admin? && get_cart != nil %>
              <li class="nav-item nav-link">
                <button class="fk-nav "><%= link_to "Cart", user_cart_path(current_user.id, get_cart.id), class: "nav-link" %></button>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KittensMarket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>